package ec.edu.espe.saturn.model;
// Generated 11/10/2017 8:52:27 by Hibernate Tools 4.3.1



/**
 * GoremalId generated by hbm2java
 */
public class GoremalId  implements java.io.Serializable {


     private int goremalPidm;
     private String goremalEmalCode;
     private String goremalEmailAddress;

    public GoremalId() {
    }

    public GoremalId(int goremalPidm, String goremalEmalCode, String goremalEmailAddress) {
       this.goremalPidm = goremalPidm;
       this.goremalEmalCode = goremalEmalCode;
       this.goremalEmailAddress = goremalEmailAddress;
    }
   
    public int getGoremalPidm() {
        return this.goremalPidm;
    }
    
    public void setGoremalPidm(int goremalPidm) {
        this.goremalPidm = goremalPidm;
    }
    public String getGoremalEmalCode() {
        return this.goremalEmalCode;
    }
    
    public void setGoremalEmalCode(String goremalEmalCode) {
        this.goremalEmalCode = goremalEmalCode;
    }
    public String getGoremalEmailAddress() {
        return this.goremalEmailAddress;
    }
    
    public void setGoremalEmailAddress(String goremalEmailAddress) {
        this.goremalEmailAddress = goremalEmailAddress;
    }




}


