package ec.edu.espe.saturn.model;
// Generated Oct 11, 2017 9:11:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Goremal generated by hbm2java
 */
public class Goremal  implements java.io.Serializable {


     private GoremalId id;
     private String goremalStatusInd;
     private String goremalPreferredInd;
     private Date goremalActivityDate;
     private String goremalUserId;
     private String goremalComment;
     private String goremalDispWebInd;
     private String goremalDataOrigin;

    public Goremal() {
        this.id = new GoremalId();
    }

	
    public Goremal(GoremalId id, String goremalStatusInd, String goremalPreferredInd, Date goremalActivityDate, String goremalUserId, String goremalDispWebInd) {
        this.id = id;
        this.goremalStatusInd = goremalStatusInd;
        this.goremalPreferredInd = goremalPreferredInd;
        this.goremalActivityDate = goremalActivityDate;
        this.goremalUserId = goremalUserId;
        this.goremalDispWebInd = goremalDispWebInd;
    }
    public Goremal(GoremalId id, String goremalStatusInd, String goremalPreferredInd, Date goremalActivityDate, String goremalUserId, String goremalComment, String goremalDispWebInd, String goremalDataOrigin) {
       this.id = id;
       this.goremalStatusInd = goremalStatusInd;
       this.goremalPreferredInd = goremalPreferredInd;
       this.goremalActivityDate = goremalActivityDate;
       this.goremalUserId = goremalUserId;
       this.goremalComment = goremalComment;
       this.goremalDispWebInd = goremalDispWebInd;
       this.goremalDataOrigin = goremalDataOrigin;
    }
   
    public GoremalId getId() {
        return this.id;
    }
    
    public void setId(GoremalId id) {
        this.id = id;
    }
    public String getGoremalStatusInd() {
        return this.goremalStatusInd;
    }
    
    public void setGoremalStatusInd(String goremalStatusInd) {
        this.goremalStatusInd = goremalStatusInd;
    }
    public String getGoremalPreferredInd() {
        return this.goremalPreferredInd;
    }
    
    public void setGoremalPreferredInd(String goremalPreferredInd) {
        this.goremalPreferredInd = goremalPreferredInd;
    }
    public Date getGoremalActivityDate() {
        return this.goremalActivityDate;
    }
    
    public void setGoremalActivityDate(Date goremalActivityDate) {
        this.goremalActivityDate = goremalActivityDate;
    }
    public String getGoremalUserId() {
        return this.goremalUserId;
    }
    
    public void setGoremalUserId(String goremalUserId) {
        this.goremalUserId = goremalUserId;
    }
    public String getGoremalComment() {
        return this.goremalComment;
    }
    
    public void setGoremalComment(String goremalComment) {
        this.goremalComment = goremalComment;
    }
    public String getGoremalDispWebInd() {
        return this.goremalDispWebInd;
    }
    
    public void setGoremalDispWebInd(String goremalDispWebInd) {
        this.goremalDispWebInd = goremalDispWebInd;
    }
    public String getGoremalDataOrigin() {
        return this.goremalDataOrigin;
    }
    
    public void setGoremalDataOrigin(String goremalDataOrigin) {
        this.goremalDataOrigin = goremalDataOrigin;
    }

    @Override
    public String toString() {
        return "Goremal{" + "id=" + id.toString() + ", goremalStatusInd=" + goremalStatusInd + ", goremalPreferredInd=" + goremalPreferredInd + ", goremalActivityDate=" + goremalActivityDate + ", goremalUserId=" + goremalUserId + ", goremalComment=" + goremalComment + ", goremalDispWebInd=" + goremalDispWebInd + ", goremalDataOrigin=" + goremalDataOrigin + '}';
    }

}


