package ec.edu.espe.saturn.model;
// Generated 27-oct-2017 9:54:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NbrjobsId generated by hbm2java
 */
public class NbrjobsId  implements java.io.Serializable {


     private int nbrjobsPidm;
     private String nbrjobsPosn;
     private String nbrjobsSuff;
     private Date nbrjobsEffectiveDate;

    public NbrjobsId() {
    }

    public NbrjobsId(int nbrjobsPidm, String nbrjobsPosn, String nbrjobsSuff, Date nbrjobsEffectiveDate) {
       this.nbrjobsPidm = nbrjobsPidm;
       this.nbrjobsPosn = nbrjobsPosn;
       this.nbrjobsSuff = nbrjobsSuff;
       this.nbrjobsEffectiveDate = nbrjobsEffectiveDate;
    }
   
    public int getNbrjobsPidm() {
        return this.nbrjobsPidm;
    }
    
    public void setNbrjobsPidm(int nbrjobsPidm) {
        this.nbrjobsPidm = nbrjobsPidm;
    }
    public String getNbrjobsPosn() {
        return this.nbrjobsPosn;
    }
    
    public void setNbrjobsPosn(String nbrjobsPosn) {
        this.nbrjobsPosn = nbrjobsPosn;
    }
    public String getNbrjobsSuff() {
        return this.nbrjobsSuff;
    }
    
    public void setNbrjobsSuff(String nbrjobsSuff) {
        this.nbrjobsSuff = nbrjobsSuff;
    }
    public Date getNbrjobsEffectiveDate() {
        return this.nbrjobsEffectiveDate;
    }
    
    public void setNbrjobsEffectiveDate(Date nbrjobsEffectiveDate) {
        this.nbrjobsEffectiveDate = nbrjobsEffectiveDate;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NbrjobsId) ) return false;
		 NbrjobsId castOther = ( NbrjobsId ) other; 
         
		 return (this.getNbrjobsPidm()==castOther.getNbrjobsPidm())
 && ( (this.getNbrjobsPosn()==castOther.getNbrjobsPosn()) || ( this.getNbrjobsPosn()!=null && castOther.getNbrjobsPosn()!=null && this.getNbrjobsPosn().equals(castOther.getNbrjobsPosn()) ) )
 && ( (this.getNbrjobsSuff()==castOther.getNbrjobsSuff()) || ( this.getNbrjobsSuff()!=null && castOther.getNbrjobsSuff()!=null && this.getNbrjobsSuff().equals(castOther.getNbrjobsSuff()) ) )
 && ( (this.getNbrjobsEffectiveDate()==castOther.getNbrjobsEffectiveDate()) || ( this.getNbrjobsEffectiveDate()!=null && castOther.getNbrjobsEffectiveDate()!=null && this.getNbrjobsEffectiveDate().equals(castOther.getNbrjobsEffectiveDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getNbrjobsPidm();
         result = 37 * result + ( getNbrjobsPosn() == null ? 0 : this.getNbrjobsPosn().hashCode() );
         result = 37 * result + ( getNbrjobsSuff() == null ? 0 : this.getNbrjobsSuff().hashCode() );
         result = 37 * result + ( getNbrjobsEffectiveDate() == null ? 0 : this.getNbrjobsEffectiveDate().hashCode() );
         return result;
   }   


}


