package ec.edu.espe.saturn.model;
// Generated 27-oct-2017 9:54:16 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PerapptId generated by hbm2java
 */
public class PerapptId  implements java.io.Serializable {


     private int perapptPidm;
     private Date perapptActionDate;
     private String perapptOrgn;
     private String perapptCoasCode;
     private String perapptPosn;
     private String perapptSuff;
     private Date perapptBeginDate;
     private Date perapptEndDate;
     private Date perapptApptEffDate;
     private Date perapptNextDate;
     private String perapptTenureCode;
     private String perapptInitialTenure;
     private Date perapptTenureEffDate;
     private Date perapptTenureTracBeginDate;
     private Date perapptTenureRevDate;
     private String perapptRevtTenureCode;
     private String perapptRevtReappCode;
     private BigDecimal perapptCredit;
     private String perapptTerminalAppt;
     private Date perapptDecisionDeferDate;
     private String perapptDecision;
     private Date perapptDecisionDate;
     private String perapptComment;
     private String perapptDispCode;
     private String perapptFtypCode;
     private BigDecimal perapptPrevGrtTenr;
     private Date perapptAppealDate;
     private Date perapptActivityDate;
     private BigDecimal perapptTenureFte;
     private String perapptUserId;

    public PerapptId() {
    }

    public PerapptId(int perapptPidm, Date perapptActionDate, String perapptOrgn, String perapptCoasCode, String perapptPosn, String perapptSuff, Date perapptBeginDate, Date perapptEndDate, Date perapptApptEffDate, Date perapptNextDate, String perapptTenureCode, String perapptInitialTenure, Date perapptTenureEffDate, Date perapptTenureTracBeginDate, Date perapptTenureRevDate, String perapptRevtTenureCode, String perapptRevtReappCode, BigDecimal perapptCredit, String perapptTerminalAppt, Date perapptDecisionDeferDate, String perapptDecision, Date perapptDecisionDate, String perapptComment, String perapptDispCode, String perapptFtypCode, BigDecimal perapptPrevGrtTenr, Date perapptAppealDate, Date perapptActivityDate, BigDecimal perapptTenureFte, String perapptUserId) {
       this.perapptPidm = perapptPidm;
       this.perapptActionDate = perapptActionDate;
       this.perapptOrgn = perapptOrgn;
       this.perapptCoasCode = perapptCoasCode;
       this.perapptPosn = perapptPosn;
       this.perapptSuff = perapptSuff;
       this.perapptBeginDate = perapptBeginDate;
       this.perapptEndDate = perapptEndDate;
       this.perapptApptEffDate = perapptApptEffDate;
       this.perapptNextDate = perapptNextDate;
       this.perapptTenureCode = perapptTenureCode;
       this.perapptInitialTenure = perapptInitialTenure;
       this.perapptTenureEffDate = perapptTenureEffDate;
       this.perapptTenureTracBeginDate = perapptTenureTracBeginDate;
       this.perapptTenureRevDate = perapptTenureRevDate;
       this.perapptRevtTenureCode = perapptRevtTenureCode;
       this.perapptRevtReappCode = perapptRevtReappCode;
       this.perapptCredit = perapptCredit;
       this.perapptTerminalAppt = perapptTerminalAppt;
       this.perapptDecisionDeferDate = perapptDecisionDeferDate;
       this.perapptDecision = perapptDecision;
       this.perapptDecisionDate = perapptDecisionDate;
       this.perapptComment = perapptComment;
       this.perapptDispCode = perapptDispCode;
       this.perapptFtypCode = perapptFtypCode;
       this.perapptPrevGrtTenr = perapptPrevGrtTenr;
       this.perapptAppealDate = perapptAppealDate;
       this.perapptActivityDate = perapptActivityDate;
       this.perapptTenureFte = perapptTenureFte;
       this.perapptUserId = perapptUserId;
    }
   
    public int getPerapptPidm() {
        return this.perapptPidm;
    }
    
    public void setPerapptPidm(int perapptPidm) {
        this.perapptPidm = perapptPidm;
    }
    public Date getPerapptActionDate() {
        return this.perapptActionDate;
    }
    
    public void setPerapptActionDate(Date perapptActionDate) {
        this.perapptActionDate = perapptActionDate;
    }
    public String getPerapptOrgn() {
        return this.perapptOrgn;
    }
    
    public void setPerapptOrgn(String perapptOrgn) {
        this.perapptOrgn = perapptOrgn;
    }
    public String getPerapptCoasCode() {
        return this.perapptCoasCode;
    }
    
    public void setPerapptCoasCode(String perapptCoasCode) {
        this.perapptCoasCode = perapptCoasCode;
    }
    public String getPerapptPosn() {
        return this.perapptPosn;
    }
    
    public void setPerapptPosn(String perapptPosn) {
        this.perapptPosn = perapptPosn;
    }
    public String getPerapptSuff() {
        return this.perapptSuff;
    }
    
    public void setPerapptSuff(String perapptSuff) {
        this.perapptSuff = perapptSuff;
    }
    public Date getPerapptBeginDate() {
        return this.perapptBeginDate;
    }
    
    public void setPerapptBeginDate(Date perapptBeginDate) {
        this.perapptBeginDate = perapptBeginDate;
    }
    public Date getPerapptEndDate() {
        return this.perapptEndDate;
    }
    
    public void setPerapptEndDate(Date perapptEndDate) {
        this.perapptEndDate = perapptEndDate;
    }
    public Date getPerapptApptEffDate() {
        return this.perapptApptEffDate;
    }
    
    public void setPerapptApptEffDate(Date perapptApptEffDate) {
        this.perapptApptEffDate = perapptApptEffDate;
    }
    public Date getPerapptNextDate() {
        return this.perapptNextDate;
    }
    
    public void setPerapptNextDate(Date perapptNextDate) {
        this.perapptNextDate = perapptNextDate;
    }
    public String getPerapptTenureCode() {
        return this.perapptTenureCode;
    }
    
    public void setPerapptTenureCode(String perapptTenureCode) {
        this.perapptTenureCode = perapptTenureCode;
    }
    public String getPerapptInitialTenure() {
        return this.perapptInitialTenure;
    }
    
    public void setPerapptInitialTenure(String perapptInitialTenure) {
        this.perapptInitialTenure = perapptInitialTenure;
    }
    public Date getPerapptTenureEffDate() {
        return this.perapptTenureEffDate;
    }
    
    public void setPerapptTenureEffDate(Date perapptTenureEffDate) {
        this.perapptTenureEffDate = perapptTenureEffDate;
    }
    public Date getPerapptTenureTracBeginDate() {
        return this.perapptTenureTracBeginDate;
    }
    
    public void setPerapptTenureTracBeginDate(Date perapptTenureTracBeginDate) {
        this.perapptTenureTracBeginDate = perapptTenureTracBeginDate;
    }
    public Date getPerapptTenureRevDate() {
        return this.perapptTenureRevDate;
    }
    
    public void setPerapptTenureRevDate(Date perapptTenureRevDate) {
        this.perapptTenureRevDate = perapptTenureRevDate;
    }
    public String getPerapptRevtTenureCode() {
        return this.perapptRevtTenureCode;
    }
    
    public void setPerapptRevtTenureCode(String perapptRevtTenureCode) {
        this.perapptRevtTenureCode = perapptRevtTenureCode;
    }
    public String getPerapptRevtReappCode() {
        return this.perapptRevtReappCode;
    }
    
    public void setPerapptRevtReappCode(String perapptRevtReappCode) {
        this.perapptRevtReappCode = perapptRevtReappCode;
    }
    public BigDecimal getPerapptCredit() {
        return this.perapptCredit;
    }
    
    public void setPerapptCredit(BigDecimal perapptCredit) {
        this.perapptCredit = perapptCredit;
    }
    public String getPerapptTerminalAppt() {
        return this.perapptTerminalAppt;
    }
    
    public void setPerapptTerminalAppt(String perapptTerminalAppt) {
        this.perapptTerminalAppt = perapptTerminalAppt;
    }
    public Date getPerapptDecisionDeferDate() {
        return this.perapptDecisionDeferDate;
    }
    
    public void setPerapptDecisionDeferDate(Date perapptDecisionDeferDate) {
        this.perapptDecisionDeferDate = perapptDecisionDeferDate;
    }
    public String getPerapptDecision() {
        return this.perapptDecision;
    }
    
    public void setPerapptDecision(String perapptDecision) {
        this.perapptDecision = perapptDecision;
    }
    public Date getPerapptDecisionDate() {
        return this.perapptDecisionDate;
    }
    
    public void setPerapptDecisionDate(Date perapptDecisionDate) {
        this.perapptDecisionDate = perapptDecisionDate;
    }
    public String getPerapptComment() {
        return this.perapptComment;
    }
    
    public void setPerapptComment(String perapptComment) {
        this.perapptComment = perapptComment;
    }
    public String getPerapptDispCode() {
        return this.perapptDispCode;
    }
    
    public void setPerapptDispCode(String perapptDispCode) {
        this.perapptDispCode = perapptDispCode;
    }
    public String getPerapptFtypCode() {
        return this.perapptFtypCode;
    }
    
    public void setPerapptFtypCode(String perapptFtypCode) {
        this.perapptFtypCode = perapptFtypCode;
    }
    public BigDecimal getPerapptPrevGrtTenr() {
        return this.perapptPrevGrtTenr;
    }
    
    public void setPerapptPrevGrtTenr(BigDecimal perapptPrevGrtTenr) {
        this.perapptPrevGrtTenr = perapptPrevGrtTenr;
    }
    public Date getPerapptAppealDate() {
        return this.perapptAppealDate;
    }
    
    public void setPerapptAppealDate(Date perapptAppealDate) {
        this.perapptAppealDate = perapptAppealDate;
    }
    public Date getPerapptActivityDate() {
        return this.perapptActivityDate;
    }
    
    public void setPerapptActivityDate(Date perapptActivityDate) {
        this.perapptActivityDate = perapptActivityDate;
    }
    public BigDecimal getPerapptTenureFte() {
        return this.perapptTenureFte;
    }
    
    public void setPerapptTenureFte(BigDecimal perapptTenureFte) {
        this.perapptTenureFte = perapptTenureFte;
    }
    public String getPerapptUserId() {
        return this.perapptUserId;
    }
    
    public void setPerapptUserId(String perapptUserId) {
        this.perapptUserId = perapptUserId;
    }




}


