package ec.edu.espe.saturn.model;
// Generated 12/10/2017 12:38:03 by Hibernate Tools 4.3.1


// Generated 12/10/2017 12:38:03 by Hibernate Tools 4.3.1



/**
 * SfrstcrId generated by hbm2java
 */
public class SfrstcrId  implements java.io.Serializable {


     private String sfrstcrTermCode;
     private int sfrstcrPidm;
     private String sfrstcrCrn;

    public SfrstcrId() {
    }

    public SfrstcrId(String sfrstcrTermCode, int sfrstcrPidm, String sfrstcrCrn) {
       this.sfrstcrTermCode = sfrstcrTermCode;
       this.sfrstcrPidm = sfrstcrPidm;
       this.sfrstcrCrn = sfrstcrCrn;
    }
   
    public String getSfrstcrTermCode() {
        return this.sfrstcrTermCode;
    }
    
    public void setSfrstcrTermCode(String sfrstcrTermCode) {
        this.sfrstcrTermCode = sfrstcrTermCode;
    }
    public int getSfrstcrPidm() {
        return this.sfrstcrPidm;
    }
    
    public void setSfrstcrPidm(int sfrstcrPidm) {
        this.sfrstcrPidm = sfrstcrPidm;
    }
    public String getSfrstcrCrn() {
        return this.sfrstcrCrn;
    }
    
    public void setSfrstcrCrn(String sfrstcrCrn) {
        this.sfrstcrCrn = sfrstcrCrn;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SfrstcrId) ) return false;
		 SfrstcrId castOther = ( SfrstcrId ) other; 
         
		 return ( (this.getSfrstcrTermCode()==castOther.getSfrstcrTermCode()) || ( this.getSfrstcrTermCode()!=null && castOther.getSfrstcrTermCode()!=null && this.getSfrstcrTermCode().equals(castOther.getSfrstcrTermCode()) ) )
 && (this.getSfrstcrPidm()==castOther.getSfrstcrPidm())
 && ( (this.getSfrstcrCrn()==castOther.getSfrstcrCrn()) || ( this.getSfrstcrCrn()!=null && castOther.getSfrstcrCrn()!=null && this.getSfrstcrCrn().equals(castOther.getSfrstcrCrn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSfrstcrTermCode() == null ? 0 : this.getSfrstcrTermCode().hashCode() );
         result = 37 * result + this.getSfrstcrPidm();
         result = 37 * result + ( getSfrstcrCrn() == null ? 0 : this.getSfrstcrCrn().hashCode() );
         return result;
   }   

    @Override
    public String toString() {
        return "SfrstcrId{" + "sfrstcrTermCode=" + sfrstcrTermCode + ", sfrstcrPidm=" + sfrstcrPidm + ", sfrstcrCrn=" + sfrstcrCrn + '}';
    }


}


