package ec.edu.espe.saturn.model;
// Generated Sep 22, 2017 9:40:41 AM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Smrprle generated by hbm2java
 */
public class Smrprle implements java.io.Serializable {

    private String smrprleProgram;
    private String smrprleProgramDesc;
    private Date smrprleActivityDate;
    private String smrprleLevlCode;
    private String smrprleCurrInd;
    private String smrprleLockedInd;
    private String smrprleCurrRuleInd;
    private String smrprleCampCode;
    private String smrprleCollCode;
    private String smrprleDegcCode;
    private Integer smrprlePidm;
    private String smrprleLevlCodeStu;
    private String smrprleWebInd;
    private Set sobcurrs = new HashSet(0);
    private List<Sobcurr> currs = new ArrayList<>();

    public Smrprle() {
    }

    public Smrprle(String smrprleProgram, String smrprleProgramDesc, Date smrprleActivityDate, String smrprleLevlCode, String smrprleCurrInd, String smrprleLockedInd, String smrprleCurrRuleInd, String smrprleLevlCodeStu, String smrprleWebInd) {
        this.smrprleProgram = smrprleProgram;
        this.smrprleProgramDesc = smrprleProgramDesc;
        this.smrprleActivityDate = smrprleActivityDate;
        this.smrprleLevlCode = smrprleLevlCode;
        this.smrprleCurrInd = smrprleCurrInd;
        this.smrprleLockedInd = smrprleLockedInd;
        this.smrprleCurrRuleInd = smrprleCurrRuleInd;
        this.smrprleLevlCodeStu = smrprleLevlCodeStu;
        this.smrprleWebInd = smrprleWebInd;
    }

    public Smrprle(String smrprleProgram, String smrprleProgramDesc, Date smrprleActivityDate, String smrprleLevlCode, String smrprleCurrInd, String smrprleLockedInd, String smrprleCurrRuleInd, String smrprleCampCode, String smrprleCollCode, String smrprleDegcCode, Integer smrprlePidm, String smrprleLevlCodeStu, String smrprleWebInd, Set sobcurrs) {
        this.smrprleProgram = smrprleProgram;
        this.smrprleProgramDesc = smrprleProgramDesc;
        this.smrprleActivityDate = smrprleActivityDate;
        this.smrprleLevlCode = smrprleLevlCode;
        this.smrprleCurrInd = smrprleCurrInd;
        this.smrprleLockedInd = smrprleLockedInd;
        this.smrprleCurrRuleInd = smrprleCurrRuleInd;
        this.smrprleCampCode = smrprleCampCode;
        this.smrprleCollCode = smrprleCollCode;
        this.smrprleDegcCode = smrprleDegcCode;
        this.smrprlePidm = smrprlePidm;
        this.smrprleLevlCodeStu = smrprleLevlCodeStu;
        this.smrprleWebInd = smrprleWebInd;
        this.sobcurrs = sobcurrs;
    }

    public String getSmrprleProgram() {
        return this.smrprleProgram;
    }

    public void setSmrprleProgram(String smrprleProgram) {
        this.smrprleProgram = smrprleProgram;
    }

    public String getSmrprleProgramDesc() {
        return this.smrprleProgramDesc;
    }

    public void setSmrprleProgramDesc(String smrprleProgramDesc) {
        this.smrprleProgramDesc = smrprleProgramDesc;
    }

    public Date getSmrprleActivityDate() {
        return this.smrprleActivityDate;
    }

    public void setSmrprleActivityDate(Date smrprleActivityDate) {
        this.smrprleActivityDate = smrprleActivityDate;
    }

    public String getSmrprleLevlCode() {
        return this.smrprleLevlCode;
    }

    public void setSmrprleLevlCode(String smrprleLevlCode) {
        this.smrprleLevlCode = smrprleLevlCode;
    }

    public String getSmrprleCurrInd() {
        return this.smrprleCurrInd;
    }

    public void setSmrprleCurrInd(String smrprleCurrInd) {
        this.smrprleCurrInd = smrprleCurrInd;
    }

    public String getSmrprleLockedInd() {
        return this.smrprleLockedInd;
    }

    public void setSmrprleLockedInd(String smrprleLockedInd) {
        this.smrprleLockedInd = smrprleLockedInd;
    }

    public String getSmrprleCurrRuleInd() {
        return this.smrprleCurrRuleInd;
    }

    public void setSmrprleCurrRuleInd(String smrprleCurrRuleInd) {
        this.smrprleCurrRuleInd = smrprleCurrRuleInd;
    }

    public String getSmrprleCampCode() {
        return this.smrprleCampCode;
    }

    public void setSmrprleCampCode(String smrprleCampCode) {
        this.smrprleCampCode = smrprleCampCode;
    }

    public String getSmrprleCollCode() {
        return this.smrprleCollCode;
    }

    public void setSmrprleCollCode(String smrprleCollCode) {
        this.smrprleCollCode = smrprleCollCode;
    }

    public String getSmrprleDegcCode() {
        return this.smrprleDegcCode;
    }

    public void setSmrprleDegcCode(String smrprleDegcCode) {
        this.smrprleDegcCode = smrprleDegcCode;
    }

    public Integer getSmrprlePidm() {
        return this.smrprlePidm;
    }

    public void setSmrprlePidm(Integer smrprlePidm) {
        this.smrprlePidm = smrprlePidm;
    }

    public String getSmrprleLevlCodeStu() {
        return this.smrprleLevlCodeStu;
    }

    public void setSmrprleLevlCodeStu(String smrprleLevlCodeStu) {
        this.smrprleLevlCodeStu = smrprleLevlCodeStu;
    }

    public String getSmrprleWebInd() {
        return this.smrprleWebInd;
    }

    public void setSmrprleWebInd(String smrprleWebInd) {
        this.smrprleWebInd = smrprleWebInd;
    }

    public Set getSobcurrs() {
        return this.sobcurrs;
    }

    public void setSobcurrs(Set sobcurrs) {
        this.sobcurrs = sobcurrs;
    }

    public List<Sobcurr> getCurrs() {
        return currs;
    }

    public void setCurrs(List<Sobcurr> currs) {
        this.currs = currs;
    }

    @Override
    public String toString() {
        return "Smrprle{" + "smrprleProgram=" + smrprleProgram + ", smrprleProgramDesc=" + smrprleProgramDesc + ", smrprleActivityDate=" + smrprleActivityDate + ", smrprleLevlCode=" + smrprleLevlCode + ", smrprleCurrInd=" + smrprleCurrInd + ", smrprleLockedInd=" + smrprleLockedInd + ", smrprleCurrRuleInd=" + smrprleCurrRuleInd + ", smrprleCampCode=" + smrprleCampCode + ", smrprleCollCode=" + smrprleCollCode + ", smrprleDegcCode=" + smrprleDegcCode + ", smrprlePidm=" + smrprlePidm + ", smrprleLevlCodeStu=" + smrprleLevlCodeStu + ", smrprleWebInd=" + smrprleWebInd + '}';
    }
}
