package ec.edu.espe.saturn.model;
// Generated Oct 11, 2017 9:11:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sobcurr generated by hbm2java
 */
public class Sobcurr  implements java.io.Serializable {


     private int sobcurrCurrRule;
     private Smrprle smrprle;
     private String sobcurrTermCodeInit;
     private String sobcurrLevlCode;
     private Date sobcurrActivityDate;
     private String sobcurrPrimRollInd;
     private String sobcurrSecdRollInd;
     private String sobcurrLockInd;
     private String sobcurrCampCode;
     private String sobcurrCollCode;
     private String sobcurrDegcCode;

    public Sobcurr() {
        this.smrprle = new Smrprle();
    }

	
    public Sobcurr(int sobcurrCurrRule, String sobcurrTermCodeInit, String sobcurrLevlCode, Date sobcurrActivityDate, String sobcurrPrimRollInd, String sobcurrSecdRollInd, String sobcurrLockInd) {
        this.sobcurrCurrRule = sobcurrCurrRule;
        this.sobcurrTermCodeInit = sobcurrTermCodeInit;
        this.sobcurrLevlCode = sobcurrLevlCode;
        this.sobcurrActivityDate = sobcurrActivityDate;
        this.sobcurrPrimRollInd = sobcurrPrimRollInd;
        this.sobcurrSecdRollInd = sobcurrSecdRollInd;
        this.sobcurrLockInd = sobcurrLockInd;
    }
    public Sobcurr(int sobcurrCurrRule, Smrprle smrprle, String sobcurrTermCodeInit, String sobcurrLevlCode, Date sobcurrActivityDate, String sobcurrPrimRollInd, String sobcurrSecdRollInd, String sobcurrLockInd, String sobcurrCampCode, String sobcurrCollCode, String sobcurrDegcCode) {
       this.sobcurrCurrRule = sobcurrCurrRule;
       this.smrprle = smrprle;
       this.sobcurrTermCodeInit = sobcurrTermCodeInit;
       this.sobcurrLevlCode = sobcurrLevlCode;
       this.sobcurrActivityDate = sobcurrActivityDate;
       this.sobcurrPrimRollInd = sobcurrPrimRollInd;
       this.sobcurrSecdRollInd = sobcurrSecdRollInd;
       this.sobcurrLockInd = sobcurrLockInd;
       this.sobcurrCampCode = sobcurrCampCode;
       this.sobcurrCollCode = sobcurrCollCode;
       this.sobcurrDegcCode = sobcurrDegcCode;
    }
   
    public int getSobcurrCurrRule() {
        return this.sobcurrCurrRule;
    }
    
    public void setSobcurrCurrRule(int sobcurrCurrRule) {
        this.sobcurrCurrRule = sobcurrCurrRule;
    }
    public Smrprle getSmrprle() {
        return this.smrprle;
    }
    
    public void setSmrprle(Smrprle smrprle) {
        this.smrprle = smrprle;
    }
    public String getSobcurrTermCodeInit() {
        return this.sobcurrTermCodeInit;
    }
    
    public void setSobcurrTermCodeInit(String sobcurrTermCodeInit) {
        this.sobcurrTermCodeInit = sobcurrTermCodeInit;
    }
    public String getSobcurrLevlCode() {
        return this.sobcurrLevlCode;
    }
    
    public void setSobcurrLevlCode(String sobcurrLevlCode) {
        this.sobcurrLevlCode = sobcurrLevlCode;
    }
    public Date getSobcurrActivityDate() {
        return this.sobcurrActivityDate;
    }
    
    public void setSobcurrActivityDate(Date sobcurrActivityDate) {
        this.sobcurrActivityDate = sobcurrActivityDate;
    }
    public String getSobcurrPrimRollInd() {
        return this.sobcurrPrimRollInd;
    }
    
    public void setSobcurrPrimRollInd(String sobcurrPrimRollInd) {
        this.sobcurrPrimRollInd = sobcurrPrimRollInd;
    }
    public String getSobcurrSecdRollInd() {
        return this.sobcurrSecdRollInd;
    }
    
    public void setSobcurrSecdRollInd(String sobcurrSecdRollInd) {
        this.sobcurrSecdRollInd = sobcurrSecdRollInd;
    }
    public String getSobcurrLockInd() {
        return this.sobcurrLockInd;
    }
    
    public void setSobcurrLockInd(String sobcurrLockInd) {
        this.sobcurrLockInd = sobcurrLockInd;
    }
    public String getSobcurrCampCode() {
        return this.sobcurrCampCode;
    }
    
    public void setSobcurrCampCode(String sobcurrCampCode) {
        this.sobcurrCampCode = sobcurrCampCode;
    }
    public String getSobcurrCollCode() {
        return this.sobcurrCollCode;
    }
    
    public void setSobcurrCollCode(String sobcurrCollCode) {
        this.sobcurrCollCode = sobcurrCollCode;
    }
    public String getSobcurrDegcCode() {
        return this.sobcurrDegcCode;
    }
    
    public void setSobcurrDegcCode(String sobcurrDegcCode) {
        this.sobcurrDegcCode = sobcurrDegcCode;
    }

    @Override
    public String toString() {
        return "Sobcurr{" + "sobcurrCurrRule=" + sobcurrCurrRule + ", smrprle=" + smrprle + ", sobcurrTermCodeInit=" + sobcurrTermCodeInit + ", sobcurrLevlCode=" + sobcurrLevlCode + ", sobcurrActivityDate=" + sobcurrActivityDate + ", sobcurrPrimRollInd=" + sobcurrPrimRollInd + ", sobcurrSecdRollInd=" + sobcurrSecdRollInd + ", sobcurrLockInd=" + sobcurrLockInd + ", sobcurrCampCode=" + sobcurrCampCode + ", sobcurrCollCode=" + sobcurrCollCode + ", sobcurrDegcCode=" + sobcurrDegcCode + '}';
    }

}


