package ec.edu.espe.saturn.model;
// Generated 12/10/2017 13:02:22 by Hibernate Tools 4.3.1



/**
 * Spraddr generated by hbm2java
 */
public class Spraddr  implements java.io.Serializable {


     private SpraddrId id;

    public Spraddr() {
        this.id= new SpraddrId();
    }

    public Spraddr(SpraddrId id) {
       this.id = id;
    }
   
    public SpraddrId getId() {
        return this.id;
    }
    
    public void setId(SpraddrId id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "Spraddr{" + "id=" + id.toString() + '}';
    }




}


