package ec.edu.espe.saturn.model;
// Generated Oct 11, 2017 9:11:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SpraddrId generated by hbm2java
 */
public class SpraddrId  implements java.io.Serializable {


     private int spraddrPidm;
     private String spraddrAtypCode;
     private byte spraddrSeqno;
     private Date spraddrFromDate;
     private Date spraddrToDate;
     private String spraddrStreetLine1;
     private String spraddrStreetLine2;
     private String spraddrStreetLine3;
     private String spraddrCity;
     private String spraddrStatCode;
     private String spraddrZip;
     private String spraddrCntyCode;
     private String spraddrNatnCode;
     private String spraddrPhoneArea;
     private String spraddrPhoneNumber;
     private String spraddrPhoneExt;
     private String spraddrStatusInd;
     private Date spraddrActivityDate;
     private String spraddrUser;
     private String spraddrAsrcCode;
     private Byte spraddrDeliveryPoint;
     private Boolean spraddrCorrectionDigit;
     private String spraddrCarrierRoute;
     private String spraddrGstTaxId;
     private String spraddrReviewedInd;
     private String spraddrReviewedUser;
     private String spraddrDataOrigin;
     private String spraddrCtryCodePhone;
     private String spraddrHouseNumber;
     private String spraddrStreetLine4;

    public SpraddrId() {
    }

    public SpraddrId(int spraddrPidm, String spraddrAtypCode, byte spraddrSeqno, Date spraddrFromDate, Date spraddrToDate, String spraddrStreetLine1, String spraddrStreetLine2, String spraddrStreetLine3, String spraddrCity, String spraddrStatCode, String spraddrZip, String spraddrCntyCode, String spraddrNatnCode, String spraddrPhoneArea, String spraddrPhoneNumber, String spraddrPhoneExt, String spraddrStatusInd, Date spraddrActivityDate, String spraddrUser, String spraddrAsrcCode, Byte spraddrDeliveryPoint, Boolean spraddrCorrectionDigit, String spraddrCarrierRoute, String spraddrGstTaxId, String spraddrReviewedInd, String spraddrReviewedUser, String spraddrDataOrigin, String spraddrCtryCodePhone, String spraddrHouseNumber, String spraddrStreetLine4) {
       this.spraddrPidm = spraddrPidm;
       this.spraddrAtypCode = spraddrAtypCode;
       this.spraddrSeqno = spraddrSeqno;
       this.spraddrFromDate = spraddrFromDate;
       this.spraddrToDate = spraddrToDate;
       this.spraddrStreetLine1 = spraddrStreetLine1;
       this.spraddrStreetLine2 = spraddrStreetLine2;
       this.spraddrStreetLine3 = spraddrStreetLine3;
       this.spraddrCity = spraddrCity;
       this.spraddrStatCode = spraddrStatCode;
       this.spraddrZip = spraddrZip;
       this.spraddrCntyCode = spraddrCntyCode;
       this.spraddrNatnCode = spraddrNatnCode;
       this.spraddrPhoneArea = spraddrPhoneArea;
       this.spraddrPhoneNumber = spraddrPhoneNumber;
       this.spraddrPhoneExt = spraddrPhoneExt;
       this.spraddrStatusInd = spraddrStatusInd;
       this.spraddrActivityDate = spraddrActivityDate;
       this.spraddrUser = spraddrUser;
       this.spraddrAsrcCode = spraddrAsrcCode;
       this.spraddrDeliveryPoint = spraddrDeliveryPoint;
       this.spraddrCorrectionDigit = spraddrCorrectionDigit;
       this.spraddrCarrierRoute = spraddrCarrierRoute;
       this.spraddrGstTaxId = spraddrGstTaxId;
       this.spraddrReviewedInd = spraddrReviewedInd;
       this.spraddrReviewedUser = spraddrReviewedUser;
       this.spraddrDataOrigin = spraddrDataOrigin;
       this.spraddrCtryCodePhone = spraddrCtryCodePhone;
       this.spraddrHouseNumber = spraddrHouseNumber;
       this.spraddrStreetLine4 = spraddrStreetLine4;
    }
   
    public int getSpraddrPidm() {
        return this.spraddrPidm;
    }
    
    public void setSpraddrPidm(int spraddrPidm) {
        this.spraddrPidm = spraddrPidm;
    }
    public String getSpraddrAtypCode() {
        return this.spraddrAtypCode;
    }
    
    public void setSpraddrAtypCode(String spraddrAtypCode) {
        this.spraddrAtypCode = spraddrAtypCode;
    }
    public byte getSpraddrSeqno() {
        return this.spraddrSeqno;
    }
    
    public void setSpraddrSeqno(byte spraddrSeqno) {
        this.spraddrSeqno = spraddrSeqno;
    }
    public Date getSpraddrFromDate() {
        return this.spraddrFromDate;
    }
    
    public void setSpraddrFromDate(Date spraddrFromDate) {
        this.spraddrFromDate = spraddrFromDate;
    }
    public Date getSpraddrToDate() {
        return this.spraddrToDate;
    }
    
    public void setSpraddrToDate(Date spraddrToDate) {
        this.spraddrToDate = spraddrToDate;
    }
    public String getSpraddrStreetLine1() {
        return this.spraddrStreetLine1;
    }
    
    public void setSpraddrStreetLine1(String spraddrStreetLine1) {
        this.spraddrStreetLine1 = spraddrStreetLine1;
    }
    public String getSpraddrStreetLine2() {
        return this.spraddrStreetLine2;
    }
    
    public void setSpraddrStreetLine2(String spraddrStreetLine2) {
        this.spraddrStreetLine2 = spraddrStreetLine2;
    }
    public String getSpraddrStreetLine3() {
        return this.spraddrStreetLine3;
    }
    
    public void setSpraddrStreetLine3(String spraddrStreetLine3) {
        this.spraddrStreetLine3 = spraddrStreetLine3;
    }
    public String getSpraddrCity() {
        return this.spraddrCity;
    }
    
    public void setSpraddrCity(String spraddrCity) {
        this.spraddrCity = spraddrCity;
    }
    public String getSpraddrStatCode() {
        return this.spraddrStatCode;
    }
    
    public void setSpraddrStatCode(String spraddrStatCode) {
        this.spraddrStatCode = spraddrStatCode;
    }
    public String getSpraddrZip() {
        return this.spraddrZip;
    }
    
    public void setSpraddrZip(String spraddrZip) {
        this.spraddrZip = spraddrZip;
    }
    public String getSpraddrCntyCode() {
        return this.spraddrCntyCode;
    }
    
    public void setSpraddrCntyCode(String spraddrCntyCode) {
        this.spraddrCntyCode = spraddrCntyCode;
    }
    public String getSpraddrNatnCode() {
        return this.spraddrNatnCode;
    }
    
    public void setSpraddrNatnCode(String spraddrNatnCode) {
        this.spraddrNatnCode = spraddrNatnCode;
    }
    public String getSpraddrPhoneArea() {
        return this.spraddrPhoneArea;
    }
    
    public void setSpraddrPhoneArea(String spraddrPhoneArea) {
        this.spraddrPhoneArea = spraddrPhoneArea;
    }
    public String getSpraddrPhoneNumber() {
        return this.spraddrPhoneNumber;
    }
    
    public void setSpraddrPhoneNumber(String spraddrPhoneNumber) {
        this.spraddrPhoneNumber = spraddrPhoneNumber;
    }
    public String getSpraddrPhoneExt() {
        return this.spraddrPhoneExt;
    }
    
    public void setSpraddrPhoneExt(String spraddrPhoneExt) {
        this.spraddrPhoneExt = spraddrPhoneExt;
    }
    public String getSpraddrStatusInd() {
        return this.spraddrStatusInd;
    }
    
    public void setSpraddrStatusInd(String spraddrStatusInd) {
        this.spraddrStatusInd = spraddrStatusInd;
    }
    public Date getSpraddrActivityDate() {
        return this.spraddrActivityDate;
    }
    
    public void setSpraddrActivityDate(Date spraddrActivityDate) {
        this.spraddrActivityDate = spraddrActivityDate;
    }
    public String getSpraddrUser() {
        return this.spraddrUser;
    }
    
    public void setSpraddrUser(String spraddrUser) {
        this.spraddrUser = spraddrUser;
    }
    public String getSpraddrAsrcCode() {
        return this.spraddrAsrcCode;
    }
    
    public void setSpraddrAsrcCode(String spraddrAsrcCode) {
        this.spraddrAsrcCode = spraddrAsrcCode;
    }
    public Byte getSpraddrDeliveryPoint() {
        return this.spraddrDeliveryPoint;
    }
    
    public void setSpraddrDeliveryPoint(Byte spraddrDeliveryPoint) {
        this.spraddrDeliveryPoint = spraddrDeliveryPoint;
    }
    public Boolean getSpraddrCorrectionDigit() {
        return this.spraddrCorrectionDigit;
    }
    
    public void setSpraddrCorrectionDigit(Boolean spraddrCorrectionDigit) {
        this.spraddrCorrectionDigit = spraddrCorrectionDigit;
    }
    public String getSpraddrCarrierRoute() {
        return this.spraddrCarrierRoute;
    }
    
    public void setSpraddrCarrierRoute(String spraddrCarrierRoute) {
        this.spraddrCarrierRoute = spraddrCarrierRoute;
    }
    public String getSpraddrGstTaxId() {
        return this.spraddrGstTaxId;
    }
    
    public void setSpraddrGstTaxId(String spraddrGstTaxId) {
        this.spraddrGstTaxId = spraddrGstTaxId;
    }
    public String getSpraddrReviewedInd() {
        return this.spraddrReviewedInd;
    }
    
    public void setSpraddrReviewedInd(String spraddrReviewedInd) {
        this.spraddrReviewedInd = spraddrReviewedInd;
    }
    public String getSpraddrReviewedUser() {
        return this.spraddrReviewedUser;
    }
    
    public void setSpraddrReviewedUser(String spraddrReviewedUser) {
        this.spraddrReviewedUser = spraddrReviewedUser;
    }
    public String getSpraddrDataOrigin() {
        return this.spraddrDataOrigin;
    }
    
    public void setSpraddrDataOrigin(String spraddrDataOrigin) {
        this.spraddrDataOrigin = spraddrDataOrigin;
    }
    public String getSpraddrCtryCodePhone() {
        return this.spraddrCtryCodePhone;
    }
    
    public void setSpraddrCtryCodePhone(String spraddrCtryCodePhone) {
        this.spraddrCtryCodePhone = spraddrCtryCodePhone;
    }
    public String getSpraddrHouseNumber() {
        return this.spraddrHouseNumber;
    }
    
    public void setSpraddrHouseNumber(String spraddrHouseNumber) {
        this.spraddrHouseNumber = spraddrHouseNumber;
    }
    public String getSpraddrStreetLine4() {
        return this.spraddrStreetLine4;
    }
    
    public void setSpraddrStreetLine4(String spraddrStreetLine4) {
        this.spraddrStreetLine4 = spraddrStreetLine4;
    }




}


