package ec.edu.espe.saturn.model;
// Generated Oct 11, 2017 9:11:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * SpridenId generated by hbm2java
 */
public class SpridenId  implements java.io.Serializable {


     private int spridenPidm;
     private String spridenId;
     private String spridenLastName;
     private String spridenFirstName;
     private String spridenMi;
     private String spridenChangeInd;
     private String spridenEntityInd;
     private Date spridenActivityDate;
     private String spridenUser;
     private String spridenOrigin;
     private String spridenSearchLastName;
     private String spridenSearchFirstName;
     private String spridenSearchMi;
     private String spridenSoundexLastName;
     private String spridenSoundexFirstName;
     private String spridenNtypCode;
     private String spridenCreateUser;
     private Date spridenCreateDate;
     private String spridenDataOrigin;
     private String spridenCreateFdmnCode;
     private String spridenSurnamePrefix;

    public SpridenId() {
    }

    public SpridenId(int spridenPidm, String spridenId, String spridenLastName, String spridenFirstName, String spridenMi, String spridenChangeInd, String spridenEntityInd, Date spridenActivityDate, String spridenUser, String spridenOrigin, String spridenSearchLastName, String spridenSearchFirstName, String spridenSearchMi, String spridenSoundexLastName, String spridenSoundexFirstName, String spridenNtypCode, String spridenCreateUser, Date spridenCreateDate, String spridenDataOrigin, String spridenCreateFdmnCode, String spridenSurnamePrefix) {
       this.spridenPidm = spridenPidm;
       this.spridenId = spridenId;
       this.spridenLastName = spridenLastName;
       this.spridenFirstName = spridenFirstName;
       this.spridenMi = spridenMi;
       this.spridenChangeInd = spridenChangeInd;
       this.spridenEntityInd = spridenEntityInd;
       this.spridenActivityDate = spridenActivityDate;
       this.spridenUser = spridenUser;
       this.spridenOrigin = spridenOrigin;
       this.spridenSearchLastName = spridenSearchLastName;
       this.spridenSearchFirstName = spridenSearchFirstName;
       this.spridenSearchMi = spridenSearchMi;
       this.spridenSoundexLastName = spridenSoundexLastName;
       this.spridenSoundexFirstName = spridenSoundexFirstName;
       this.spridenNtypCode = spridenNtypCode;
       this.spridenCreateUser = spridenCreateUser;
       this.spridenCreateDate = spridenCreateDate;
       this.spridenDataOrigin = spridenDataOrigin;
       this.spridenCreateFdmnCode = spridenCreateFdmnCode;
       this.spridenSurnamePrefix = spridenSurnamePrefix;
    }
   
    public int getSpridenPidm() {
        return this.spridenPidm;
    }
    
    public void setSpridenPidm(int spridenPidm) {
        this.spridenPidm = spridenPidm;
    }
    public String getSpridenId() {
        return this.spridenId;
    }
    
    public void setSpridenId(String spridenId) {
        this.spridenId = spridenId;
    }
    public String getSpridenLastName() {
        return this.spridenLastName;
    }
    
    public void setSpridenLastName(String spridenLastName) {
        this.spridenLastName = spridenLastName;
    }
    public String getSpridenFirstName() {
        return this.spridenFirstName;
    }
    
    public void setSpridenFirstName(String spridenFirstName) {
        this.spridenFirstName = spridenFirstName;
    }
    public String getSpridenMi() {
        return this.spridenMi;
    }
    
    public void setSpridenMi(String spridenMi) {
        this.spridenMi = spridenMi;
    }
    public String getSpridenChangeInd() {
        return this.spridenChangeInd;
    }
    
    public void setSpridenChangeInd(String spridenChangeInd) {
        this.spridenChangeInd = spridenChangeInd;
    }
    public String getSpridenEntityInd() {
        return this.spridenEntityInd;
    }
    
    public void setSpridenEntityInd(String spridenEntityInd) {
        this.spridenEntityInd = spridenEntityInd;
    }
    public Date getSpridenActivityDate() {
        return this.spridenActivityDate;
    }
    
    public void setSpridenActivityDate(Date spridenActivityDate) {
        this.spridenActivityDate = spridenActivityDate;
    }
    public String getSpridenUser() {
        return this.spridenUser;
    }
    
    public void setSpridenUser(String spridenUser) {
        this.spridenUser = spridenUser;
    }
    public String getSpridenOrigin() {
        return this.spridenOrigin;
    }
    
    public void setSpridenOrigin(String spridenOrigin) {
        this.spridenOrigin = spridenOrigin;
    }
    public String getSpridenSearchLastName() {
        return this.spridenSearchLastName;
    }
    
    public void setSpridenSearchLastName(String spridenSearchLastName) {
        this.spridenSearchLastName = spridenSearchLastName;
    }
    public String getSpridenSearchFirstName() {
        return this.spridenSearchFirstName;
    }
    
    public void setSpridenSearchFirstName(String spridenSearchFirstName) {
        this.spridenSearchFirstName = spridenSearchFirstName;
    }
    public String getSpridenSearchMi() {
        return this.spridenSearchMi;
    }
    
    public void setSpridenSearchMi(String spridenSearchMi) {
        this.spridenSearchMi = spridenSearchMi;
    }
    public String getSpridenSoundexLastName() {
        return this.spridenSoundexLastName;
    }
    
    public void setSpridenSoundexLastName(String spridenSoundexLastName) {
        this.spridenSoundexLastName = spridenSoundexLastName;
    }
    public String getSpridenSoundexFirstName() {
        return this.spridenSoundexFirstName;
    }
    
    public void setSpridenSoundexFirstName(String spridenSoundexFirstName) {
        this.spridenSoundexFirstName = spridenSoundexFirstName;
    }
    public String getSpridenNtypCode() {
        return this.spridenNtypCode;
    }
    
    public void setSpridenNtypCode(String spridenNtypCode) {
        this.spridenNtypCode = spridenNtypCode;
    }
    public String getSpridenCreateUser() {
        return this.spridenCreateUser;
    }
    
    public void setSpridenCreateUser(String spridenCreateUser) {
        this.spridenCreateUser = spridenCreateUser;
    }
    public Date getSpridenCreateDate() {
        return this.spridenCreateDate;
    }
    
    public void setSpridenCreateDate(Date spridenCreateDate) {
        this.spridenCreateDate = spridenCreateDate;
    }
    public String getSpridenDataOrigin() {
        return this.spridenDataOrigin;
    }
    
    public void setSpridenDataOrigin(String spridenDataOrigin) {
        this.spridenDataOrigin = spridenDataOrigin;
    }
    public String getSpridenCreateFdmnCode() {
        return this.spridenCreateFdmnCode;
    }
    
    public void setSpridenCreateFdmnCode(String spridenCreateFdmnCode) {
        this.spridenCreateFdmnCode = spridenCreateFdmnCode;
    }
    public String getSpridenSurnamePrefix() {
        return this.spridenSurnamePrefix;
    }
    
    public void setSpridenSurnamePrefix(String spridenSurnamePrefix) {
        this.spridenSurnamePrefix = spridenSurnamePrefix;
    }

    @Override
    public String toString() {
        return "SpridenId{" + "spridenPidm=" + spridenPidm + ", spridenId=" + spridenId + ", spridenLastName=" + spridenLastName + ", spridenFirstName=" + spridenFirstName + ", spridenMi=" + spridenMi + ", spridenChangeInd=" + spridenChangeInd + ", spridenEntityInd=" + spridenEntityInd + ", spridenActivityDate=" + spridenActivityDate + ", spridenUser=" + spridenUser + ", spridenOrigin=" + spridenOrigin + ", spridenSearchLastName=" + spridenSearchLastName + ", spridenSearchFirstName=" + spridenSearchFirstName + ", spridenSearchMi=" + spridenSearchMi + ", spridenSoundexLastName=" + spridenSoundexLastName + ", spridenSoundexFirstName=" + spridenSoundexFirstName + ", spridenNtypCode=" + spridenNtypCode + ", spridenCreateUser=" + spridenCreateUser + ", spridenCreateDate=" + spridenCreateDate + ", spridenDataOrigin=" + spridenDataOrigin + ", spridenCreateFdmnCode=" + spridenCreateFdmnCode + ", spridenSurnamePrefix=" + spridenSurnamePrefix + '}';
    }

}


