package ec.edu.espe.saturn.model;
// Generated Oct 11, 2017 9:11:35 AM by Hibernate Tools 4.3.1



/**
 * Spriden generated by hbm2java
 */
public class Spriden  implements java.io.Serializable {


     private SpridenId id;

    public Spriden() {
        this.id = new SpridenId();
    }

    public Spriden(SpridenId id) {
       this.id = id;
    }
   
    public SpridenId getId() {
        return this.id;
    }
    
    public void setId(SpridenId id) {
        this.id = id;
    }




}


