package ec.edu.espe.saturn.model;
// Generated Oct 11, 2017 9:11:35 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Sprtele generated by hbm2java
 */
public class Sprtele  implements java.io.Serializable {


     private SprteleId id;
     private Date sprteleActivityDate;
     private String sprtelePhoneArea;
     private String sprtelePhoneNumber;
     private String sprtelePhoneExt;
     private String sprteleStatusInd;
     private String sprteleAtypCode;
     private Byte sprteleAddrSeqno;
     private String sprtelePrimaryInd;
     private String sprteleUnlistInd;
     private String sprteleComment;
     private String sprteleIntlAccess;
     private String sprteleDataOrigin;
     private String sprteleUserId;
     private String sprteleCtryCodePhone;

    public Sprtele() {
        this.id = new SprteleId();
    }

	
    public Sprtele(SprteleId id, Date sprteleActivityDate) {
        this.id = id;
        this.sprteleActivityDate = sprteleActivityDate;
    }
    public Sprtele(SprteleId id, Date sprteleActivityDate, String sprtelePhoneArea, String sprtelePhoneNumber, String sprtelePhoneExt, String sprteleStatusInd, String sprteleAtypCode, Byte sprteleAddrSeqno, String sprtelePrimaryInd, String sprteleUnlistInd, String sprteleComment, String sprteleIntlAccess, String sprteleDataOrigin, String sprteleUserId, String sprteleCtryCodePhone) {
       this.id = id;
       this.sprteleActivityDate = sprteleActivityDate;
       this.sprtelePhoneArea = sprtelePhoneArea;
       this.sprtelePhoneNumber = sprtelePhoneNumber;
       this.sprtelePhoneExt = sprtelePhoneExt;
       this.sprteleStatusInd = sprteleStatusInd;
       this.sprteleAtypCode = sprteleAtypCode;
       this.sprteleAddrSeqno = sprteleAddrSeqno;
       this.sprtelePrimaryInd = sprtelePrimaryInd;
       this.sprteleUnlistInd = sprteleUnlistInd;
       this.sprteleComment = sprteleComment;
       this.sprteleIntlAccess = sprteleIntlAccess;
       this.sprteleDataOrigin = sprteleDataOrigin;
       this.sprteleUserId = sprteleUserId;
       this.sprteleCtryCodePhone = sprteleCtryCodePhone;
    }
   
    public SprteleId getId() {
        return this.id;
    }
    
    public void setId(SprteleId id) {
        this.id = id;
    }
    public Date getSprteleActivityDate() {
        return this.sprteleActivityDate;
    }
    
    public void setSprteleActivityDate(Date sprteleActivityDate) {
        this.sprteleActivityDate = sprteleActivityDate;
    }
    public String getSprtelePhoneArea() {
        return this.sprtelePhoneArea;
    }
    
    public void setSprtelePhoneArea(String sprtelePhoneArea) {
        this.sprtelePhoneArea = sprtelePhoneArea;
    }
    public String getSprtelePhoneNumber() {
        return this.sprtelePhoneNumber;
    }
    
    public void setSprtelePhoneNumber(String sprtelePhoneNumber) {
        this.sprtelePhoneNumber = sprtelePhoneNumber;
    }
    public String getSprtelePhoneExt() {
        return this.sprtelePhoneExt;
    }
    
    public void setSprtelePhoneExt(String sprtelePhoneExt) {
        this.sprtelePhoneExt = sprtelePhoneExt;
    }
    public String getSprteleStatusInd() {
        return this.sprteleStatusInd;
    }
    
    public void setSprteleStatusInd(String sprteleStatusInd) {
        this.sprteleStatusInd = sprteleStatusInd;
    }
    public String getSprteleAtypCode() {
        return this.sprteleAtypCode;
    }
    
    public void setSprteleAtypCode(String sprteleAtypCode) {
        this.sprteleAtypCode = sprteleAtypCode;
    }
    public Byte getSprteleAddrSeqno() {
        return this.sprteleAddrSeqno;
    }
    
    public void setSprteleAddrSeqno(Byte sprteleAddrSeqno) {
        this.sprteleAddrSeqno = sprteleAddrSeqno;
    }
    public String getSprtelePrimaryInd() {
        return this.sprtelePrimaryInd;
    }
    
    public void setSprtelePrimaryInd(String sprtelePrimaryInd) {
        this.sprtelePrimaryInd = sprtelePrimaryInd;
    }
    public String getSprteleUnlistInd() {
        return this.sprteleUnlistInd;
    }
    
    public void setSprteleUnlistInd(String sprteleUnlistInd) {
        this.sprteleUnlistInd = sprteleUnlistInd;
    }
    public String getSprteleComment() {
        return this.sprteleComment;
    }
    
    public void setSprteleComment(String sprteleComment) {
        this.sprteleComment = sprteleComment;
    }
    public String getSprteleIntlAccess() {
        return this.sprteleIntlAccess;
    }
    
    public void setSprteleIntlAccess(String sprteleIntlAccess) {
        this.sprteleIntlAccess = sprteleIntlAccess;
    }
    public String getSprteleDataOrigin() {
        return this.sprteleDataOrigin;
    }
    
    public void setSprteleDataOrigin(String sprteleDataOrigin) {
        this.sprteleDataOrigin = sprteleDataOrigin;
    }
    public String getSprteleUserId() {
        return this.sprteleUserId;
    }
    
    public void setSprteleUserId(String sprteleUserId) {
        this.sprteleUserId = sprteleUserId;
    }
    public String getSprteleCtryCodePhone() {
        return this.sprteleCtryCodePhone;
    }
    
    public void setSprteleCtryCodePhone(String sprteleCtryCodePhone) {
        this.sprteleCtryCodePhone = sprteleCtryCodePhone;
    }

    @Override
    public String toString() {
        return "Sprtele{" + "id=" + id.toString() + ", sprteleActivityDate=" + sprteleActivityDate + ", sprtelePhoneArea=" + sprtelePhoneArea + ", sprtelePhoneNumber=" + sprtelePhoneNumber + ", sprtelePhoneExt=" + sprtelePhoneExt + ", sprteleStatusInd=" + sprteleStatusInd + ", sprteleAtypCode=" + sprteleAtypCode + ", sprteleAddrSeqno=" + sprteleAddrSeqno + ", sprtelePrimaryInd=" + sprtelePrimaryInd + ", sprteleUnlistInd=" + sprteleUnlistInd + ", sprteleComment=" + sprteleComment + ", sprteleIntlAccess=" + sprteleIntlAccess + ", sprteleDataOrigin=" + sprteleDataOrigin + ", sprteleUserId=" + sprteleUserId + ", sprteleCtryCodePhone=" + sprteleCtryCodePhone + '}';
    }

}


