package ec.edu.espe.saturn.model;
// Generated 12/10/2017 13:02:22 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Stvcamp generated by hbm2java
 */
public class Stvcamp implements java.io.Serializable {

    
    private String stvcampCode;
    private String stvcampDesc;
    private Date stvcampActivityDate;
    private String stvcampDicdCode;
    private Set sgbstdnsForSgbstdnCampCode2 = new HashSet(0);
    private Set sobcurrs = new HashSet(0);
    private Set smrprles = new HashSet(0);
    private Set sgbstdnsForSgbstdnCampCode = new HashSet(0);
    private Set sfrstcrs = new HashSet(0);
    private List<Sgbstdn> sgbstdnsforsgbstdncampcode2sa = new ArrayList<>();
    private List<Sobcurr> sobcurrsa = new ArrayList<>();
    private List<Smrprle> smrprlesa = new ArrayList<>();
    private List<Sgbstdn> sgbstdnsforsgbstdncampcodesa = new ArrayList<>();
    private List<Sfrstcr> sfrstcrsa = new ArrayList<>();

    public Stvcamp() {
        this.sgbstdnsforsgbstdncampcode2sa = new ArrayList<>();
        this.sobcurrsa = new ArrayList<>();
        this.smrprlesa = new ArrayList<>();
        this.sgbstdnsforsgbstdncampcodesa = new ArrayList<>();
        this.sfrstcrsa = new ArrayList<>();

    }

    
    public Stvcamp(String stvcampCode, Date stvcampActivityDate) {
        this.stvcampCode = stvcampCode;
        this.stvcampActivityDate = stvcampActivityDate;
    }

    public Stvcamp(String stvcampCode, String stvcampDesc, Date stvcampActivityDate, String stvcampDicdCode, Set sgbstdnsForSgbstdnCampCode2, Set sobcurrs, Set smrprles, Set sgbstdnsForSgbstdnCampCode, Set sfrstcrs) {
        this.stvcampCode = stvcampCode;
        this.stvcampDesc = stvcampDesc;
        this.stvcampActivityDate = stvcampActivityDate;
        this.stvcampDicdCode = stvcampDicdCode;
        this.sgbstdnsForSgbstdnCampCode2 = sgbstdnsForSgbstdnCampCode2;
        this.sobcurrs = sobcurrs;
        this.smrprles = smrprles;
        this.sgbstdnsForSgbstdnCampCode = sgbstdnsForSgbstdnCampCode;
        this.sfrstcrs = sfrstcrs;
    }

    public String getStvcampCode() {
        return this.stvcampCode;
    }

    public void setStvcampCode(String stvcampCode) {
        this.stvcampCode = stvcampCode;
    }

    public String getStvcampDesc() {
        return this.stvcampDesc;
    }

    public void setStvcampDesc(String stvcampDesc) {
        this.stvcampDesc = stvcampDesc;
    }

    public Date getStvcampActivityDate() {
        return this.stvcampActivityDate;
    }

    public void setStvcampActivityDate(Date stvcampActivityDate) {
        this.stvcampActivityDate = stvcampActivityDate;
    }

    public String getStvcampDicdCode() {
        return this.stvcampDicdCode;
    }

    public void setStvcampDicdCode(String stvcampDicdCode) {
        this.stvcampDicdCode = stvcampDicdCode;
    }

    public Set getSgbstdnsForSgbstdnCampCode2() {
        return this.sgbstdnsForSgbstdnCampCode2;
    }

    public void setSgbstdnsForSgbstdnCampCode2(Set sgbstdnsForSgbstdnCampCode2) {
        this.sgbstdnsForSgbstdnCampCode2 = sgbstdnsForSgbstdnCampCode2;
    }

    public Set getSobcurrs() {
        return this.sobcurrs;
    }

    public void setSobcurrs(Set sobcurrs) {
        this.sobcurrs = sobcurrs;
    }

    public Set getSmrprles() {
        return this.smrprles;
    }

    public void setSmrprles(Set smrprles) {
        this.smrprles = smrprles;
    }

    public Set getSgbstdnsForSgbstdnCampCode() {
        return this.sgbstdnsForSgbstdnCampCode;
    }

    public void setSgbstdnsForSgbstdnCampCode(Set sgbstdnsForSgbstdnCampCode) {
        this.sgbstdnsForSgbstdnCampCode = sgbstdnsForSgbstdnCampCode;
    }

    public Set getSfrstcrs() {
        return this.sfrstcrs;
    }

    public void setSfrstcrs(Set sfrstcrs) {
        this.sfrstcrs = sfrstcrs;
    }

    public List<Sgbstdn> getSgbstdnsforsgbstdncampcode2() {
        return sgbstdnsforsgbstdncampcode2sa;
    }

    public void setSgbstdnsforsgbstdncampcode2(List<Sgbstdn> sgbstdnsforsgbstdncampcode2) {
        this.sgbstdnsforsgbstdncampcode2sa = sgbstdnsforsgbstdncampcode2;
    }

    public List<Sobcurr> getSobcurr() {
        return sobcurrsa;
    }

    public void setSobcurr(List<Sobcurr> sobcurr) {
        this.sobcurrsa = sobcurr;
    }

    public List<Smrprle> getSmrprle() {
        return smrprlesa;
    }

    public void setSmrprle(List<Smrprle> smrprle) {
        this.smrprlesa = smrprle;
    }

    public List<Sgbstdn> getSgbstdnsforsgbstdncampcode() {
        return sgbstdnsforsgbstdncampcodesa;
    }

    public void setSgbstdnsforsgbstdncampcode(List<Sgbstdn> sgbstdnsforsgbstdncampcode) {
        this.sgbstdnsforsgbstdncampcodesa = sgbstdnsforsgbstdncampcode;
    }

    public List<Sfrstcr> getSfrstcr() {
        return sfrstcrsa;
    }

    public void setSfrstcr(List<Sfrstcr> sfrstcr) {
        this.sfrstcrsa = sfrstcr;
    }

    @Override
    public String toString() {
        return "Stvcamp{" + "stvcampCode=" + stvcampCode + ", stvcampDesc=" + stvcampDesc + ", stvcampActivityDate=" + stvcampActivityDate + ", stvcampDicdCode=" + stvcampDicdCode + '}';
    }


}
