package ec.edu.espe.saturn.model;
// Generated 12/10/2017 13:02:22 by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Stvcoll generated by hbm2java
 */
public class Stvcoll implements java.io.Serializable {

    private String stvcollCode;
    private String stvcollDesc;
    private String stvcollAddrStreetLine1;
    private String stvcollAddrStreetLine2;
    private String stvcollAddrStreetLine3;
    private String stvcollAddrCity;
    private String stvcollAddrState;
    private String stvcollAddrCountry;
    private String stvcollAddrZipCode;
    private Date stvcollActivityDate;
    private String stvcollSystemReqInd;
    private Integer stvcollVrMsgNo;
    private String stvcollStatscanCde3;
    private String stvcollDicdCode;
    private String stvcollHouseNumber;
    private String stvcollAddrStreetLine4;
    private Set sgbstdnsForSgbstdnCollCode2 = new HashSet(0);
    private Set sgbstdnsForSgbstdnCollCode1 = new HashSet(0);
    private Set smrprles = new HashSet(0);
    private Set sgbstdnsForSgbstdnCollCodeDual = new HashSet(0);
    private Set sobcurrs = new HashSet(0);
    private List<Sgbstdn> sgbstdnsforsgbstdncollcode2 = new ArrayList<>();
    private List<Sgbstdn> sgbstdnsforsgbstdncollcode1 = new ArrayList<>();
    private List<Smrprle> smrprless = new ArrayList<>();
    private List<Sgbstdn> sgbstdnsforsgbstdncollcodedual = new ArrayList<>();
    private List<Sobcurr> sobcurrss = new ArrayList<>();

    public Stvcoll() {
        this.sgbstdnsforsgbstdncollcode2 = new ArrayList<>();
        this.sgbstdnsforsgbstdncollcode1 = new ArrayList<>();
        this.smrprless = new ArrayList<>();
        this.sgbstdnsforsgbstdncollcodedual = new ArrayList<>();
        this.sobcurrss = new ArrayList<>();
    }

    public Stvcoll(String stvcollCode, String stvcollDesc) {
        this.stvcollCode = stvcollCode;
        this.stvcollDesc = stvcollDesc;
    }

    public Stvcoll(String stvcollCode, String stvcollDesc, String stvcollAddrStreetLine1, String stvcollAddrStreetLine2, String stvcollAddrStreetLine3, String stvcollAddrCity, String stvcollAddrState, String stvcollAddrCountry, String stvcollAddrZipCode, Date stvcollActivityDate, String stvcollSystemReqInd, Integer stvcollVrMsgNo, String stvcollStatscanCde3, String stvcollDicdCode, String stvcollHouseNumber, String stvcollAddrStreetLine4, Set sgbstdnsForSgbstdnCollCode2, Set sgbstdnsForSgbstdnCollCode1, Set smrprles, Set sgbstdnsForSgbstdnCollCodeDual, Set sobcurrs) {
        this.stvcollCode = stvcollCode;
        this.stvcollDesc = stvcollDesc;
        this.stvcollAddrStreetLine1 = stvcollAddrStreetLine1;
        this.stvcollAddrStreetLine2 = stvcollAddrStreetLine2;
        this.stvcollAddrStreetLine3 = stvcollAddrStreetLine3;
        this.stvcollAddrCity = stvcollAddrCity;
        this.stvcollAddrState = stvcollAddrState;
        this.stvcollAddrCountry = stvcollAddrCountry;
        this.stvcollAddrZipCode = stvcollAddrZipCode;
        this.stvcollActivityDate = stvcollActivityDate;
        this.stvcollSystemReqInd = stvcollSystemReqInd;
        this.stvcollVrMsgNo = stvcollVrMsgNo;
        this.stvcollStatscanCde3 = stvcollStatscanCde3;
        this.stvcollDicdCode = stvcollDicdCode;
        this.stvcollHouseNumber = stvcollHouseNumber;
        this.stvcollAddrStreetLine4 = stvcollAddrStreetLine4;
        this.sgbstdnsForSgbstdnCollCode2 = sgbstdnsForSgbstdnCollCode2;
        this.sgbstdnsForSgbstdnCollCode1 = sgbstdnsForSgbstdnCollCode1;
        this.smrprles = smrprles;
        this.sgbstdnsForSgbstdnCollCodeDual = sgbstdnsForSgbstdnCollCodeDual;
        this.sobcurrs = sobcurrs;
    }

    public String getStvcollCode() {
        return this.stvcollCode;
    }

    public void setStvcollCode(String stvcollCode) {
        this.stvcollCode = stvcollCode;
    }

    public String getStvcollDesc() {
        return this.stvcollDesc;
    }

    public void setStvcollDesc(String stvcollDesc) {
        this.stvcollDesc = stvcollDesc;
    }

    public String getStvcollAddrStreetLine1() {
        return this.stvcollAddrStreetLine1;
    }

    public void setStvcollAddrStreetLine1(String stvcollAddrStreetLine1) {
        this.stvcollAddrStreetLine1 = stvcollAddrStreetLine1;
    }

    public String getStvcollAddrStreetLine2() {
        return this.stvcollAddrStreetLine2;
    }

    public void setStvcollAddrStreetLine2(String stvcollAddrStreetLine2) {
        this.stvcollAddrStreetLine2 = stvcollAddrStreetLine2;
    }

    public String getStvcollAddrStreetLine3() {
        return this.stvcollAddrStreetLine3;
    }

    public void setStvcollAddrStreetLine3(String stvcollAddrStreetLine3) {
        this.stvcollAddrStreetLine3 = stvcollAddrStreetLine3;
    }

    public String getStvcollAddrCity() {
        return this.stvcollAddrCity;
    }

    public void setStvcollAddrCity(String stvcollAddrCity) {
        this.stvcollAddrCity = stvcollAddrCity;
    }

    public String getStvcollAddrState() {
        return this.stvcollAddrState;
    }

    public void setStvcollAddrState(String stvcollAddrState) {
        this.stvcollAddrState = stvcollAddrState;
    }

    public String getStvcollAddrCountry() {
        return this.stvcollAddrCountry;
    }

    public void setStvcollAddrCountry(String stvcollAddrCountry) {
        this.stvcollAddrCountry = stvcollAddrCountry;
    }

    public String getStvcollAddrZipCode() {
        return this.stvcollAddrZipCode;
    }

    public void setStvcollAddrZipCode(String stvcollAddrZipCode) {
        this.stvcollAddrZipCode = stvcollAddrZipCode;
    }

    public Date getStvcollActivityDate() {
        return this.stvcollActivityDate;
    }

    public void setStvcollActivityDate(Date stvcollActivityDate) {
        this.stvcollActivityDate = stvcollActivityDate;
    }

    public String getStvcollSystemReqInd() {
        return this.stvcollSystemReqInd;
    }

    public void setStvcollSystemReqInd(String stvcollSystemReqInd) {
        this.stvcollSystemReqInd = stvcollSystemReqInd;
    }

    public Integer getStvcollVrMsgNo() {
        return this.stvcollVrMsgNo;
    }

    public void setStvcollVrMsgNo(Integer stvcollVrMsgNo) {
        this.stvcollVrMsgNo = stvcollVrMsgNo;
    }

    public String getStvcollStatscanCde3() {
        return this.stvcollStatscanCde3;
    }

    public void setStvcollStatscanCde3(String stvcollStatscanCde3) {
        this.stvcollStatscanCde3 = stvcollStatscanCde3;
    }

    public String getStvcollDicdCode() {
        return this.stvcollDicdCode;
    }

    public void setStvcollDicdCode(String stvcollDicdCode) {
        this.stvcollDicdCode = stvcollDicdCode;
    }

    public String getStvcollHouseNumber() {
        return this.stvcollHouseNumber;
    }

    public void setStvcollHouseNumber(String stvcollHouseNumber) {
        this.stvcollHouseNumber = stvcollHouseNumber;
    }

    public String getStvcollAddrStreetLine4() {
        return this.stvcollAddrStreetLine4;
    }

    public void setStvcollAddrStreetLine4(String stvcollAddrStreetLine4) {
        this.stvcollAddrStreetLine4 = stvcollAddrStreetLine4;
    }

    public Set getSgbstdnsForSgbstdnCollCode2() {
        return this.sgbstdnsForSgbstdnCollCode2;
    }

    public void setSgbstdnsForSgbstdnCollCode2(Set sgbstdnsForSgbstdnCollCode2) {
        this.sgbstdnsForSgbstdnCollCode2 = sgbstdnsForSgbstdnCollCode2;
    }

    public Set getSgbstdnsForSgbstdnCollCode1() {
        return this.sgbstdnsForSgbstdnCollCode1;
    }

    public void setSgbstdnsForSgbstdnCollCode1(Set sgbstdnsForSgbstdnCollCode1) {
        this.sgbstdnsForSgbstdnCollCode1 = sgbstdnsForSgbstdnCollCode1;
    }

    public Set getSmrprles() {
        return this.smrprles;
    }

    public void setSmrprles(Set smrprles) {
        this.smrprles = smrprles;
    }

    public Set getSgbstdnsForSgbstdnCollCodeDual() {
        return this.sgbstdnsForSgbstdnCollCodeDual;
    }

    public void setSgbstdnsForSgbstdnCollCodeDual(Set sgbstdnsForSgbstdnCollCodeDual) {
        this.sgbstdnsForSgbstdnCollCodeDual = sgbstdnsForSgbstdnCollCodeDual;
    }

    public Set getSobcurrs() {
        return this.sobcurrs;
    }

    public void setSobcurrs(Set sobcurrs) {
        this.sobcurrs = sobcurrs;
    }

    public List<Sgbstdn> getSgbstdnsforsgbstdncollcode2() {
        return sgbstdnsforsgbstdncollcode2;
    }

    public void setSgbstdnsforsgbstdncollcode2(List<Sgbstdn> sgbstdnsforsgbstdncollcode2) {
        this.sgbstdnsforsgbstdncollcode2 = sgbstdnsforsgbstdncollcode2;
    }

    public List<Sgbstdn> getSgbstdnsforsgbstdncollcode1() {
        return sgbstdnsforsgbstdncollcode1;
    }

    public void setSgbstdnsforsgbstdncollcode1(List<Sgbstdn> sgbstdnsforsgbstdncollcode1) {
        this.sgbstdnsforsgbstdncollcode1 = sgbstdnsforsgbstdncollcode1;
    }

    public List<Smrprle> getSmrprless() {
        return smrprless;
    }

    public void setSmrprless(List<Smrprle> smrprless) {
        this.smrprless = smrprless;
    }

    public List<Sgbstdn> getSgbstdnsforsgbstdncollcodedual() {
        return sgbstdnsforsgbstdncollcodedual;
    }

    public void setSgbstdnsforsgbstdncollcodedual(List<Sgbstdn> sgbstdnsforsgbstdncollcodedual) {
        this.sgbstdnsforsgbstdncollcodedual = sgbstdnsforsgbstdncollcodedual;
    }

    public List<Sobcurr> getSobcurrss() {
        return sobcurrss;
    }

    public void setSobcurrss(List<Sobcurr> sobcurrss) {
        this.sobcurrss = sobcurrss;
    }

    @Override
    public String toString() {
        return "Stvcoll{" + "stvcollCode=" + stvcollCode + ", stvcollDesc=" + stvcollDesc + ", stvcollAddrStreetLine1=" + stvcollAddrStreetLine1 + ", stvcollAddrStreetLine2=" + stvcollAddrStreetLine2 + ", stvcollAddrStreetLine3=" + stvcollAddrStreetLine3 + ", stvcollAddrCity=" + stvcollAddrCity + ", stvcollAddrState=" + stvcollAddrState + ", stvcollAddrCountry=" + stvcollAddrCountry + ", stvcollAddrZipCode=" + stvcollAddrZipCode + ", stvcollActivityDate=" + stvcollActivityDate + ", stvcollSystemReqInd=" + stvcollSystemReqInd + ", stvcollVrMsgNo=" + stvcollVrMsgNo + ", stvcollStatscanCde3=" + stvcollStatscanCde3 + ", stvcollDicdCode=" + stvcollDicdCode + ", stvcollHouseNumber=" + stvcollHouseNumber + ", stvcollAddrStreetLine4=" + stvcollAddrStreetLine4 + '}';
    }

   

    
}
